{{- if eq ( include "trustification.application.collector.enabled" . ) "true" }}
{{ if .Values.collector.deployment.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "trustification.common.name" ( dict "root" . "name" "otel-collector" ) }}
spec:
  mode: {{ .Values.collector.deployment.mode | default "deployment" }}
  observability:
    metrics:
      enableMetrics: {{ include "trustification.application.metrics.enabled" . }}
  config:

{{ with .Values.collector.deployment.config }}{{ . | toYaml | nindent 4 }}{{ else }}

    receivers:

{{- if eq ( include "trustification.application.metrics.enabled" . ) "true" }}
      otlp:
        protocols:
          grpc:
          http:
{{ end }}

    exporters:

{{- if eq ( include "trustification.application.metrics.enabled" . ) "true" }}
      prometheus:
        endpoint: 0.0.0.0:8889
        resource_to_telemetry_conversion:
          enabled: true # by default resource attributes are dropped
{{ end }}

    service:
      telemetry:
        metrics:
          address: ":8888"
      pipelines:

{{- if eq ( include "trustification.application.metrics.enabled" . ) "true" }}
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
{{ end }}

{{ end }}{{/* with config */}}

{{ end }}
{{ end }}
