# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - jaeger=https://jaegertracing.github.io/helm-charts
  - open-telemetry=https://open-telemetry.github.io/opentelemetry-helm-charts
helm-extra-args: --timeout 600s --values values-minikube.yaml -set-string appDomain=.localhost
helm-lint-extra-args: --values values-minikube.yaml --set-string appDomain=.localhost
