appDomain: change-me
partOf: trustify
replicas: 1

image:
  name: trustd
  registry: ghcr.io/trustification
  pullPolicy: IfNotPresent

rust: {}

ingress: {}

tls: {}

storage: {}

database: {}

openshift:
  useServiceCa: true

oidc:
  clients:
    frontend: {}
    cli:
      clientSecret:

serviceMonitor:
  enabled: false

infrastructure:
  port: 9010

metrics:
  enabled: false

tracing:
  enabled: false

collector: ""

modules:
  server:
    enabled: true
    replicas: 1
    ingress: {}
    image: {}
    infrastructure: {}
    tracing: {}
    metrics: {}
    rust: {}

  importer:
    enabled: true
    replicas: 1
    image: {}
    infrastructure: {}
    tracing: {}
    metrics: {}
    rust: {}
    concurrency: 1

  createDatabase:
    enabled: false
    image:
      name: postgres
      registry: docker.io/library
      version: "17.2"

  migrateDatabase:
    enabled: false
    image: {}

  createImporters:
    enabled: false
    image:
      name: postgres
      registry: docker.io/library
      version: "17.2"
    importers: {}
