appDomain: change-me
partOf: trustify
replicas: 1

image:
  name: trustd
  registry: ghcr.io/trustification
  pullPolicy: IfNotPresent

rust: {}

ingress:
  enabled: true

tls: {}

storage: {}

database: {}

openshift:
  useServiceCa: true

oidc:
  clients:
    frontend: {}
    cli:
      clientSecret:

infrastructure:
  port: 9010

metrics:
  enabled: false

tracing:
  enabled: false

collector:
  endpoint: "http://trustify-collector:4317"

modules:
  server:
    enabled: true
    replicas: 1
    ingress: {}
    image: {}
    infrastructure: {}
    tracing: {}
    metrics: {}
    rust: {}
    resources:
      requests:
        cpu: 1
        memory: 8Gi

  importer:
    enabled: true
    replicas: 1
    image: {}
    infrastructure: {}
    tracing: {}
    metrics: {}
    rust: {}
    resources:
      requests:
        cpu: 1
        memory: 8Gi
    concurrency: 1
    workingDirectory:
      size: 32Gi

  createDatabase:
    enabled: false
    image:
      name: postgres
      registry: docker.io/library
      version: "17.2"

  migrateDatabase:
    enabled: false
    image: {}

  createImporters:
    enabled: false
    image:
      name: postgres
      registry: docker.io/library
      version: "17.2"
    importers: {}

  collector:
    enabled: false
    replicas: 1
    image:
      name: opentelemetry-collector-contrib
      registry: docker.io/otel
      version: "0.136.0"
    infrastructure: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
