apiVersion: v2
name: trustify-infrastructure
description: A Helm chart for setting up self-hosted infrastructure components for using Trustify

maintainers:
  - name: ctron
    email: jreimann@redhat.com

type: application
version: 0.1.1
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/trustification/trustification/main/docs/branding/svg/trustification_icon_default.svg
home: https://trustification.io

# **NOTE:** Because of Helm dependency hell, all those versions must be in sync! In case of transient dependencies,
# like keycloak -> postgres -> common, one might end up with different versions of those transient dependencies. If
# that's the case, then it might just crash and burn, as Helm can't handle different versions of the same chart.

# **NOTE:** Also because of Helm dependency Hell, it is not possible to enable keycloak and postgresql at the same
# time. The reason is that both installations will create the same resources, creating a conflict in the deployment.
# When enabling keycloak, you automatically enable postgresql too. In order to use postgresql when keycloak is disabled,
# you can still enable postgresql independently.

dependencies:
  - name: keycloak
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 22.0.0
    condition: keycloak.enabled
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.0.0
    condition: postgresql.enabled
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: 3.3.3
    condition: jaeger.enabled
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.111.1
    condition: opentelemetry-collector.enabled
