# If you wish to add additional configuration parameters to the create-database, uncomment the section below
# The example below contains configuration for logging queries with duration longer than 500ms
# postgresql:
#   primary:
#     extendedConfiguration: |-
#       log_min_duration_statement = 500
postgresql:
  enabled: false

keycloak:
  enabled: false

jaeger:
  enabled: false

keycloakPostInstall:
  disabled: false
  # NOTE: this must be an image which contain things like bash, kcadm, grep, awk
  image: docker.io/bitnami/keycloak:23
  kcadmPath: /opt/bitnami/keycloak/bin/kcadm.sh
  realmAdmin:
    name: admin
    password: admin123456
  redirectUrls: []
  identityProviders:
    github: {}

oidc:
  clients: {}

env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector-contrib"
  enabled: true
  nameOverride: otelcol
  mode: deployment
  presets:
    kubernetesAttributes:
      enabled: true
  service:
    type: ClusterIP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
    exporters:
      otlp:
        endpoint: 'http://{{ .Release.Name }}-jaeger-collector:4317'
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          exporters: [otlp]
          processors: [batch]
          receivers: [otlp]
