{{- if .Values.modules.collector.enabled }}
{{- $mod := dict "root" . "name" "collector" "component" "collector" "module" .Values.modules.collector -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trustification.common.name" $mod }}-config
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}

data:
  otelcol-contrib.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
        send_batch_max_size: 2048
      
      memory_limiter:
        limit_mib: 256
        spike_limit_mib: 128
        check_interval: 5s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "trustify"
        const_labels:
          service: "trustify"
      
      debug:
        verbosity: normal

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
{{ end }}